In [2]:
import pandas as pd
import gzip
import os

---

<h1><center>Bussiness Google</center></h1>

<h1><center>Lectura de informacion</center></h1>

El primer paso antes de realizar la normalizacion y limpieza de los datasets correspondientes a los metadatos de google, fue unificar los ya mencionados datasets para luego proceder a realizar la exportacion de los mismos

In [2]:
# En este bloque, realize la apertura de todos los .json de meta datos de google, para luego concatenarlos y formar un solo dataframe con toda la informacion
'''
dicc = {}

for x in range(1,12):
    dicc[x] = pd.read_json(f'extras\Google Maps\metadata-sitios\{x}.json', lines=True)
    
    
# Lista para almacenar los DataFrames
lista_dataframes = []

# Iterar sobre los valores del diccionario (los Datasets<.json>)
for df in dicc.values():
    lista_dataframes.append(df)

# Concatenar los DataFrames en uno solo
resultado_concatenado = pd.concat(lista_dataframes, ignore_index=True)

'''

### Cabe aclarar que este bloque de comandos solo se utiliza en primera instancia, ya que luego se trabajara sobre la exportacion unificada

In [3]:
#resultado_concatenado.head()

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,Porter Pharmacy,"Porter Pharmacy, 129 N Second St, Cochran, GA ...",0x88f16e41928ff687:0x883dad4fd048e8f8,None,32.388300,-83.357100,[Pharmacy],4.9,16,None,"[[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...","{'Service options': ['In-store shopping', 'Sam...",Open ⋅ Closes 6PM,"[0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...",https://www.google.com/maps/place//data=!4m2!3...
1,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,None,34.018891,-118.215290,[Textile exporter],4.5,6,None,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
2,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,None,34.058092,-118.292130,[Korean restaurant],4.4,18,None,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM,"[0x80c2c78249aba68f:0x35bf16ce61be751d, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
3,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,None,34.023669,-118.232930,[Fabric store],3.3,6,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM,"[0x80c2c8811477253f:0x23a8a492df1918f7, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
4,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,None,34.036694,-118.249421,[Fabric store],4.3,7,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM,"[0x80c2c62c496083d1:0xdefa11317fe870a1, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...

In [3]:
# Lectura de dataset unificado
meta_datos_google = pd.read_json(r'..\extras\google Maps\metadata-sitios\bussiness_google.json.gz')
meta_datos_google.head()

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,Porter Pharmacy,"Porter Pharmacy, 129 N Second St, Cochran, GA ...",0x88f16e41928ff687:0x883dad4fd048e8f8,None,32.388300,-83.357100,[Pharmacy],4.9,16,None,"[[Friday, 8AM–6PM], [Saturday, 8AM–12PM], [Sun...","{'Service options': ['In-store shopping', 'Sam...",Open ⋅ Closes 6PM,"[0x88f16e41929435cf:0x5b2532a2885e9ef6, 0x88f1...",https://www.google.com/maps/place//data=!4m2!3...
1,City Textile,"City Textile, 3001 E Pico Blvd, Los Angeles, C...",0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,None,34.018891,-118.215290,[Textile exporter],4.5,6,None,None,None,Open now,"[0x80c2c624136ea88b:0xb0315367ed448771, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
2,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,None,34.058092,-118.292130,[Korean restaurant],4.4,18,None,"[[Thursday, 6:30AM–6PM], [Friday, 6:30AM–6PM],...","{'Service options': ['Takeout', 'Dine-in', 'De...",Open ⋅ Closes 6PM,"[0x80c2c78249aba68f:0x35bf16ce61be751d, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
3,Nova Fabrics,"Nova Fabrics, 2200 E 11th St, Los Angeles, CA ...",0x80c2c89923b27a41:0x32041559418d447,None,34.023669,-118.232930,[Fabric store],3.3,6,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...","{'Service options': ['In-store shopping'], 'Pa...",Open ⋅ Closes 5PM,"[0x80c2c8811477253f:0x23a8a492df1918f7, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...
4,Nobel Textile Co,"Nobel Textile Co, 719 E 9th St, Los Angeles, C...",0x80c2c632f933b073:0xc31785961fe826a6,None,34.036694,-118.249421,[Fabric store],4.3,7,None,"[[Thursday, 9AM–5PM], [Friday, 9AM–5PM], [Satu...",{'Service options': ['In-store pickup']},Open ⋅ Closes 5PM,"[0x80c2c62c496083d1:0xdefa11317fe870a1, 0x80c2...",https://www.google.com/maps/place//data=!4m2!3...

In [10]:
print(resultado_concatenado.columns.values)

['name' 'address' 'gmap_id' 'description' 'latitude' 'longitude'
 'category' 'avg_rating' 'num_of_reviews' 'price' 'hours' 'MISC' 'state'
 'relative_results' 'url']

## Columnas eliminadas

-state (por que no es relevante, dice si esta habierto el local o no en base al dia y )

-url (se puede ingresar utilizando la siguiente url mas el gmap-id) [https://www.google.com/maps/place//data=!4m2!3m1!1s {aca va el gmap_id}]

-description (esta informacion podemos obtenerla en caso de ser necesario usando la api, solo tiene 250.000 datos lo que vuelve a la columna irrelevante en comparacion con la cantidad total, por eso mismo se recomienda realizar la extraccion de dicha columna de ser necesario desde la api)

-MISC (esta columna tenia una descripcion de como estan las condiciones del local)

-price (es irrelevante el precio)

-num_of_reviews (esta columna tendremos que volver a crearla luego de realizar el etl de los estados)

-address (esta informacion podemos extraerla del url en el caso de ser necesario)

-hours (en caso de ser necesario se extraeran los datos especificos de la url)

-relative_result (podemos obtener el mismo resultado y hasta mas eficiente realizando una ponderacion de los valores de latitude y longitude)

Muestra de acceso a google maps por medio de url mas gmap_id:

https://www.google.com/maps/place//data=!4m2!3m1!1s0x88e77e406e2da09d:0x479c876de5fd4ec4

In [ ]:
resultado_concatenado.drop(columns=['state','url','description','MISC','price','num_of_reviews','address','hours','relative_results'],inplace=True)

In [11]:
resultado_concatenado

,name,gmap_id,latitude,longitude,category,avg_rating
0,Porter Pharmacy,0x88f16e41928ff687:0x883dad4fd048e8f8,32.388300,-83.357100,[Pharmacy],4.9
1,City Textile,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,34.018891,-118.215290,[Textile exporter],4.5
2,San Soo Dang,0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,[Korean restaurant],4.4
3,Nova Fabrics,0x80c2c89923b27a41:0x32041559418d447,34.023669,-118.232930,[Fabric store],3.3
4,Nobel Textile Co,0x80c2c632f933b073:0xc31785961fe826a6,34.036694,-118.249421,[Fabric store],4.3
...,...,...,...,...,...,...
3025006,Steak 48,0x89c6c74f43a49b55:0x6be6995921c58b12,39.947254,-75.164953,"[Steak house, Fine dining restaurant, Seafood ...",4.6
3025007,"Jack Mcnerney Chevrolet, Inc.",0x89da1787d3fdc4a5:0xce92ea6e3cd4d1cc,42.788636,-76.122120,[Chevrolet dealer],4.4
3025008,Central Ny Spay Neuter Assista,0x89da6b9ce832726f:0xbd0d3630f1e3b42e,42.603831,-76.165286,[Veterinarian],4.3
3025009,Ok Feed Store,0x88d9e872a9e39f3d:0x5de29f50507e5d73,25.491641,-80.456076,[Animal feed store],4.9
3025010,Crestview Crossing,0x54956b3944b1654d:0x7797cead9a485c22,45.310254,-122.935500,[Lodging],5.0

In [12]:
df_limites_estados = pd.read_csv(r'..\datasets\raw\limites_estados.csv')

In [13]:
# Definir la función verificar_limite_empresa para que funcione con el DataFrame de empresas
def verificar_limite_empresa(row, df_limites_estados):
    latitud = row['latitude']
    longitud = row['longitude']
    estado_perteneciente = None  # Inicializar el estado_perteneciente como None
    
    # Iterar sobre cada fila del DataFrame de límites de estados
    for index, state_row in df_limites_estados.iterrows():
        lat_min, lat_max = state_row['lat_min'], state_row['lat_max']
        lon_min, lon_max = state_row['lon_min'], state_row['lon_max']
        
        # Verificar si las coordenadas están dentro de los límites del estado actual
        dentro_de_limites = (lat_min <= latitud <= lat_max) and (lon_min <= longitud <= lon_max)
        
        # Si las coordenadas están dentro de los límites, obtener el nombre del estado
        if dentro_de_limites:
            estado_perteneciente = state_row['estado']
            break  # Romper el bucle una vez que se encuentra el estado
    
    return estado_perteneciente

In [15]:
otro = pd.read_csv(r'..\extras\google Maps\metadata-sitios\all_in_one_limpio_con_nombres.csv.gz')

In [18]:
# Aplicar la función verificar_limite_empresa a cada fila del DataFrame de empresas
resultado_concatenado['Estado_Perteneciente'] = resultado_concatenado.apply(verificar_limite_empresa, df_limites_estados=df_limites_estados, axis=1)
resultado_concatenado

,gmap_id,latitude,longitude,category,avg_rating,Estado_Perteneciente,name
0,0x88f16e41928ff687:0x883dad4fd048e8f8,32.388300,-83.357100,['Pharmacy'],4.9,Georgia,Porter Pharmacy
1,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,34.018891,-118.215290,['Textile exporter'],4.5,California,City Textile
2,0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,['Korean restaurant'],4.4,California,San Soo Dang
3,0x80c2c89923b27a41:0x32041559418d447,34.023669,-118.232930,['Fabric store'],3.3,California,Nova Fabrics
4,0x80c2c632f933b073:0xc31785961fe826a6,34.036694,-118.249421,['Fabric store'],4.3,California,Nobel Textile Co
...,...,...,...,...,...,...,...
2970361,0x89c6c74f43a49b55:0x6be6995921c58b12,39.947254,-75.164953,['Steak house' 'Fine dining restaurant' 'Seafo...,4.6,New Jersey,Steak 48
2970362,0x89da1787d3fdc4a5:0xce92ea6e3cd4d1cc,42.788636,-76.122120,['Chevrolet dealer'],4.4,New York,"Jack Mcnerney Chevrolet, Inc."
2970363,0x89da6b9ce832726f:0xbd0d3630f1e3b42e,42.603831,-76.165286,['Veterinarian'],4.3,New York,Central Ny Spay Neuter Assista
2970364,0x88d9e872a9e39f3d:0x5de29f50507e5d73,25.491641,-80.456076,['Animal feed store'],4.9,Florida,Ok Feed Store
2970365,0x54956b3944b1654d:0x7797cead9a485c22,45.310254,-122.935500,['Lodging'],5.0,Oregon,Crestview Crossing

In [20]:
'''

# Suponiendo que 'json' es tu DataFrame
resultado_concatenado.to_json(r'..\extras\Google Maps\metadata-sitios\bussiness_google.json', index=False)

# Ruta del archivo CSV que quieres comprimir con gzip
input_file = r'..\extras\Google Maps\metadata-sitios\bussiness_google.json'

# Ruta de salida para el archivo comprimido con gzip
output_file = r'..\extras\Google Maps\metadata-sitios\bussiness_google.json.gz'

# Comprimir el archivo CSV usando gzip
with open(input_file, 'rb') as f_in:
    with gzip.open(output_file, 'wb') as f_out:
        f_out.writelines(f_in)

# Eliminar el archivo json original si se desea
os.remove(input_file)

'''

In [22]:
bussiness_google = pd.read_json(r'..\extras\Google Maps\metadata-sitios\bussiness_google.json.gz')
bussiness_google

,gmap_id,latitude,longitude,category,avg_rating,Estado_Perteneciente,name
0,0x88f16e41928ff687:0x883dad4fd048e8f8,32.388300,-83.357100,['Pharmacy'],4.9,Georgia,Porter Pharmacy
1,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,34.018891,-118.215290,['Textile exporter'],4.5,California,City Textile
2,0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,['Korean restaurant'],4.4,California,San Soo Dang
3,0x80c2c89923b27a41:0x32041559418d447,34.023669,-118.232930,['Fabric store'],3.3,California,Nova Fabrics
4,0x80c2c632f933b073:0xc31785961fe826a6,34.036694,-118.249421,['Fabric store'],4.3,California,Nobel Textile Co
...,...,...,...,...,...,...,...
2970361,0x89c6c74f43a49b55:0x6be6995921c58b12,39.947254,-75.164953,['Steak house' 'Fine dining restaurant' 'Seafo...,4.6,New Jersey,Steak 48
2970362,0x89da1787d3fdc4a5:0xce92ea6e3cd4d1cc,42.788636,-76.122120,['Chevrolet dealer'],4.4,New York,"Jack Mcnerney Chevrolet, Inc."
2970363,0x89da6b9ce832726f:0xbd0d3630f1e3b42e,42.603831,-76.165286,['Veterinarian'],4.3,New York,Central Ny Spay Neuter Assista
2970364,0x88d9e872a9e39f3d:0x5de29f50507e5d73,25.491641,-80.456076,['Animal feed store'],4.9,Florida,Ok Feed Store
2970365,0x54956b3944b1654d:0x7797cead9a485c22,45.310254,-122.935500,['Lodging'],5.0,Oregon,Crestview Crossing

---

<h1><center>Bussiness Yelp</center></h1>

<h1><center>Lectura de informacion</center></h1>

In [32]:
bussiness_yelp = pd.read_pickle(r'..\extras\yelp\business.pkl')

In [33]:
bussiness_yelp.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,NaN,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,NaN,63123,38.551126,-90.335695,3.0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,NaN,85711,32.223236,-110.880452,3.5,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,18054,40.338183,-75.471659,4.5,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
bussiness_yelp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150346 entries, 0 to 150345
Data columns (total 28 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   address       150346 non-null  object
 3   city          150346 non-null  object
 4   state         150343 non-null  object
 5   postal_code   150346 non-null  object
 6   latitude      150346 non-null  object
 7   longitude     150346 non-null  object
 8   stars         150346 non-null  object
 9   review_count  150346 non-null  object
 10  is_open       150346 non-null  object
 11  attributes    136602 non-null  object
 12  categories    150243 non-null  object
 13  hours         127123 non-null  object
 14  business_id   5 non-null       object
 15  name          5 non-null       object
 16  address       5 non-null       object
 17  city          5 non-null       object
 18  state         5 non-null       object
 19  postal_code   5 non-null       object
 20  latitude      5 non-null       object
 21  longitude     5 non-null       object
 22  stars         5 non-null       object
 23  review_count  5 non-null       object
 24  is_open       5 non-null       object
 25  attributes    5 non-null       object
 26  categories    5 non-null       object
 27  hours         5 non-null       object
dtypes: object(28)
memory usage: 33.3+ MB

In [35]:
bussiness_yelp = bussiness_yelp.iloc[::,:14].copy()

In [37]:
bussiness_yelp.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,NaN,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,NaN,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,NaN,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."