In [1]:
import pandas as pd
import numpy as np
import os
import json
import ijson
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import gzip

In [24]:
meta = pd.read_parquet(r'datasets\Google Maps\metadata-sitios\all_in_one_limpio_dummies.parquet')

In [38]:
estados = pd.read_parquet(r'datasets\Google Maps\reviews-estados\Estados\all_Arizona.parquet')

In [32]:
meta

,gmap_id,latitude,longitude,category,avg_rating,Estado_Perteneciente,Restaurant,Auto repair shop,Gas station,Service establishment,Beauty salon,Convenience store,Church,Hair salon,Nail salon,ATM,Park,Doctor,Clothing store,Dentist
0,0x88f16e41928ff687:0x883dad4fd048e8f8,32.388300,-83.357100,['Pharmacy'],4.9,Georgia,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,34.018891,-118.215290,['Textile exporter'],4.5,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,['Korean restaurant'],4.4,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0x80c2c89923b27a41:0x32041559418d447,34.023669,-118.232930,['Fabric store'],3.3,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0x80c2c632f933b073:0xc31785961fe826a6,34.036694,-118.249421,['Fabric store'],4.3,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996590,0x89c6c74f43a49b55:0x6be6995921c58b12,39.947254,-75.164953,['Steak house' 'Fine dining restaurant' 'Seafo...,4.6,New Jersey,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996591,0x89da1787d3fdc4a5:0xce92ea6e3cd4d1cc,42.788636,-76.122120,['Chevrolet dealer'],4.4,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996592,0x89da6b9ce832726f:0xbd0d3630f1e3b42e,42.603831,-76.165286,['Veterinarian'],4.3,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996593,0x88d9e872a9e39f3d:0x5de29f50507e5d73,25.491641,-80.456076,['Animal feed store'],4.9,Florida,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996594,0x54956b3944b1654d:0x7797cead9a485c22,45.310254,-122.935500,['Lodging'],5.0,Oregon,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [37]:
estados

,user_id,name,time,rating,text,pics,gmap_id,resp_time,resp_text
0,1.091298e+20,Nicki Gore,2019-08-20 20:12:31.619,5,We always stay here when in Valdez for silver ...,None,0x56b646ed2220b77f:0xd8975e316de80952,NaT,None
1,1.132409e+20,Allen Ratliff,2017-09-09 00:46:22.385,5,Great campground for the price. Nice hot unlim...,None,0x56b646ed2220b77f:0xd8975e316de80952,NaT,None
2,1.130448e+20,Jonathan Tringali,2016-09-25 01:11:41.185,4,We tent camped here for 2 nights while explori...,None,0x56b646ed2220b77f:0xd8975e316de80952,NaT,None
3,1.103292e+20,S Blad,2016-09-02 23:22:15.682,4,"This place is just a few miles outside Valdez,...",None,0x56b646ed2220b77f:0xd8975e316de80952,NaT,None
4,1.089896e+20,Daniel Formoso,2018-06-22 06:43:31.341,5,Probably the nicest and cleanest campground we...,None,0x56b646ed2220b77f:0xd8975e316de80952,NaT,None
...,...,...,...,...,...,...,...,...,...
521510,1.063779e+20,Emily Stanker,2020-07-23 00:27:30.942,3,None,None,0x540c25a454fb47cf:0xf0788e2fb7ba1907,NaT,None
521511,1.182198e+20,Jeri Hill,2019-11-13 01:22:51.589,3,None,None,0x540c25a454fb47cf:0xf0788e2fb7ba1907,NaT,None
521512,1.170553e+20,Stas Moszynski,2018-03-08 04:05:04.459,3,None,None,0x540c25a454fb47cf:0xf0788e2fb7ba1907,NaT,None
521513,1.130331e+20,Kalli Kline,2021-01-30 19:51:41.339,4,None,None,0x540c25a454fb47cf:0xf0788e2fb7ba1907,NaT,None
521514,1.091719e+20,Ed ThePopPunkKid,2019-10-14 15:52:14.950,5,None,None,0x540c25a454fb47cf:0xf0788e2fb7ba1907,NaT,None

In [17]:
# Crear un DataFrame de listas de múltiples valores y expandirlo
df_expanded = meta.explode('category')

# Definir la lista de categorías de interés
categories_of_interest = ['Restaurant', 'Auto repair shop', 'Gas station', 'Service establishment', 'Beauty salon', 'Convenience store', 'Church', 'Hair salon', 'Nail salon', 'ATM', 'Park', 'Doctor', 'Clothing store', 'Dentist']

# Crear una columna para cada categoría de interés con valores 0 como valor inicial
for category in categories_of_interest:
    meta[category] = 0

# Marcar con 1 las columnas correspondientes a las categorías presentes en la lista 'category'
for category in categories_of_interest:
    meta[category] = meta['category'].apply(lambda x: 1 if category in x else 0)

meta

,gmap_id,latitude,longitude,category,avg_rating,Estado_Perteneciente,Restaurant,Auto repair shop,Gas station,Service establishment,Beauty salon,Convenience store,Church,Hair salon,Nail salon,ATM,Park,Doctor,Clothing store,Dentist
0,0x88f16e41928ff687:0x883dad4fd048e8f8,32.388300,-83.357100,['Pharmacy'],4.9,Georgia,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0x80c2c98c0e3c16fd:0x29ec8a728764fdf9,34.018891,-118.215290,['Textile exporter'],4.5,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,['Korean restaurant'],4.4,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0x80c2c89923b27a41:0x32041559418d447,34.023669,-118.232930,['Fabric store'],3.3,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0x80c2c632f933b073:0xc31785961fe826a6,34.036694,-118.249421,['Fabric store'],4.3,California,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996590,0x89c6c74f43a49b55:0x6be6995921c58b12,39.947254,-75.164953,['Steak house' 'Fine dining restaurant' 'Seafo...,4.6,New Jersey,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996591,0x89da1787d3fdc4a5:0xce92ea6e3cd4d1cc,42.788636,-76.122120,['Chevrolet dealer'],4.4,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996592,0x89da6b9ce832726f:0xbd0d3630f1e3b42e,42.603831,-76.165286,['Veterinarian'],4.3,New York,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996593,0x88d9e872a9e39f3d:0x5de29f50507e5d73,25.491641,-80.456076,['Animal feed store'],4.9,Florida,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2996594,0x54956b3944b1654d:0x7797cead9a485c22,45.310254,-122.935500,['Lodging'],5.0,Oregon,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [18]:
merged_df = pd.merge(estados, meta, on='gmap_id', how='left')

In [21]:
# Sumar el número de ocurrencias de cada categoría
count_categories = merged_df.iloc[:, 14:].sum()

count_categories

Restaurant               103948.0
Auto repair shop          21883.0
Gas station               27887.0
Service establishment      1378.0
Beauty salon              13234.0
Convenience store         20989.0
Church                     6059.0
Hair salon                11828.0
Nail salon                13714.0
ATM                        5808.0
Park                      12255.0
Doctor                     3185.0
Clothing store            31526.0
Dentist                    5683.0
dtype: float64

In [51]:
import os
import pandas as pd

def procesar_archivos_parquet(ruta_carpeta, meta):
    resultados = []  # Lista para almacenar los resultados como diccionarios

    # Iterar sobre cada archivo en la carpeta
    for archivo in os.listdir(ruta_carpeta):
        if archivo.endswith('.parquet'):  # Verificar si es un archivo Parquet
            ruta_archivo = os.path.join(ruta_carpeta, archivo)  # Obtener la ruta completa del archivo
            try:
                # Leer el archivo Parquet como DataFrame
                estados = pd.read_parquet(ruta_archivo)

                merged_df = pd.merge(estados, meta, on='gmap_id', how='left')

                count_categories = merged_df.iloc[:, 14:].sum()

                # Almacenar el resultado específico como un diccionario
                resultado = {'Archivo': archivo, **count_categories.to_dict()}
                resultados.append(resultado)

            except Exception as e:
                print(f"Error al procesar {archivo}: {e}")
    
    return resultados

# Llamada a la función con la ruta de la carpeta 'estados' y el DataFrame 'estados'
resultados_procesados = procesar_archivos_parquet(r'datasets\Google Maps\reviews-estados\Estados', meta)

# Convertir la lista de diccionarios a un DataFrame
df = pd.DataFrame(resultados_procesados)

# Guardar el DataFrame como archivo CSV
df.to_parquet('cantidad_locales_por_estado.parquet', index=False)

In [52]:
df

,Archivo,Restaurant,Auto repair shop,Gas station,Service establishment,Beauty salon,Convenience store,Church,Hair salon,Nail salon,ATM,Park,Doctor,Clothing store,Dentist
0,all_Alabama.parquet,103948.0,21883.0,27887.0,1378.0,13234.0,20989.0,6059.0,11828.0,13714.0,5808.0,12255.0,3185.0,31526.0,5683.0
1,all_Alaska.parquet,9781.0,2856.0,2009.0,99.0,1550.0,445.0,650.0,1355.0,1041.0,266.0,1993.0,80.0,1375.0,769.0
2,all_Arizona.parquet,179946.0,37691.0,22691.0,5791.0,25268.0,22016.0,8282.0,22365.0,29946.0,12843.0,20486.0,8082.0,42661.0,17598.0
3,all_Arkansas.parquet,55150.0,11870.0,20058.0,594.0,7449.0,16487.0,2893.0,6829.0,8497.0,2262.0,9169.0,899.0,14034.0,4216.0
4,all_California.parquet,395627.0,72972.0,41946.0,6841.0,63366.0,29637.0,15666.0,48411.0,59304.0,13832.0,78442.0,5549.0,77876.0,19073.0
5,all_Colorado.parquet,154348.0,32079.0,23710.0,5394.0,21366.0,13420.0,6253.0,22315.0,20321.0,7403.0,35273.0,5121.0,35480.0,15433.0
6,all_Connecticut.parquet,70797.0,15775.0,10854.0,956.0,8093.0,4165.0,1818.0,7475.0,9057.0,1531.0,12921.0,2929.0,13902.0,2653.0
7,all_Delaware.parquet,15957.0,3927.0,2592.0,211.0,2539.0,1857.0,524.0,2389.0,3181.0,530.0,1891.0,402.0,9933.0,1014.0
8,all_District_of_Columbia.parquet,9242.0,180.0,727.0,0.0,1784.0,643.0,327.0,1216.0,1455.0,77.0,1893.0,72.0,1056.0,125.0
9,all_Florida.parquet,552898.0,63210.0,34139.0,16725.0,46816.0,37721.0,15125.0,43037.0,50180.0,22611.0,53433.0,14892.0,88054.0,30884.0
10,all_Georgia.parquet,280075.0,49292.0,41965.0,6561.0,36864.0,37527.0,11895.0,35985.0,41507.0,15648.0,35520.0,8917.0,71058.0,20706.0
11,all_Hawaii.parquet,30790.0,3701.0,2438.0,162.0,1915.0,846.0,971.0,2003.0,1563.0,443.0,13073.0,115.0,5213.0,598.0
12,all_Idaho.parquet,32459.0,8336.0,6678.0,1158.0,6386.0,3353.0,4646.0,5149.0,4893.0,1321.0,6100.0,1021.0,11170.0,3653.0
13,all_Illinois.parquet,274190.0,60345.0,39807.0,3285.0,41424.0,34886.0,9455.0,40150.0,36503.0,14881.0,65453.0,3901.0,65712.0,17134.0
14,all_Indiana.parquet,145024.0,30960.0,28305.0,1853.0,21202.0,22187.0,8831.0,18706.0,20270.0,6423.0,31540.0,1680.0,42161.0,10346.0
15,all_Iowa.parquet,68407.0,13137.0,13165.0,647.0,8354.0,15333.0,2307.0,7074.0,7228.0,1495.0,15625.0,400.0,15813.0,2270.0
16,all_Kansas.parquet,55576.0,12698.0,11426.0,1344.0,8966.0,10052.0,3731.0,7858.0,7992.0,1893.0,13461.0,767.0,8029.0,3374.0
17,all_Kentucky.parquet,79831.0,15189.0,17806.0,875.0,9766.0,18515.0,3897.0,8753.0,10306.0,6341.0,11730.0,1201.0,25160.0,3976.0
18,all_Louisiana.parquet,91737.0,15421.0,23439.0,924.0,8904.0,19441.0,3185.0,8679.0,12202.0,4724.0,17139.0,1121.0,25539.0,4150.0
19,all_Maine.parquet,26634.0,6894.0,5917.0,309.0,2464.0,3170.0,540.0,2496.0,1855.0,1437.0,4317.0,125.0,4739.0,961.0
20,all_Maryland.parquet,139051.0,28360.0,17214.0,1426.0,15690.0,11909.0,5139.0,17188.0,19597.0,4314.0,22372.0,2855.0,39513.0,7816.0
21,all_Massachusetts.parquet,132576.0,28457.0,15957.0,1294.0,17527.0,6891.0,3201.0,15494.0,16990.0,1907.0,21995.0,1651.0,18673.0,5501.0
22,all_Michigan.parquet,265451.0,54842.0,41924.0,4886.0,40966.0,28609.0,11118.0,38611.0,35475.0,15675.0,56126.0,5199.0,50499.0,17392.0
23,all_Minnesota.parquet,109795.0,26908.0,24154.0,1925.0,18216.0,18930.0,6364.0,19063.0,16233.0,4774.0,40833.0,1058.0,23160.0,4724.0
24,all_Mississippi.parquet,45285.0,7669.0,17045.0,257.0,4045.0,16842.0,1701.0,3137.0,5282.0,3294.0,4868.0,771.0,13304.0,1538.0
25,all_Missouri.parquet,154748.0,32114.0,30924.0,1956.0,19712.0,27727.0,8458.0,18175.0,20231.0,6334.0,35847.0,1992.0,36805.0,8019.0
26,all_Montana.parquet,15044.0,4577.0,5101.0,200.0,3864.0,987.0,919.0,3095.0,2950.0,731.0,6059.0,210.0,5325.0,1050.0
27,all_Nebraska.parquet,44840.0,8673.0,8871.0,620.0,5971.0,8368.0,2129.0,5926.0,5541.0,1961.0,7600.0,831.0,13477.0,2682.0
28,all_Nevada.parquet,55681.0,11615.0,8891.0,1356.0,10921.0,7569.0,2300.0,8078.0,10591.0,3195.0,9607.0,2235.0,9196.0,4848.0
29,all_New_Hampshire.parquet,25433.0,9231.0,4675.0,228.0,4641.0,1947.0,839.0,5066.0,3549.0,447.0,5041.0,238.0,3851.0,1501.0
30,all_New_Jersey.parquet,202578.0,39354.0,20609.0,1644.0,31559.0,16108.0,4994.0,28248.0,30836.0,5448.0,36499.0,3967.0,38466.0,9573.0
31,all_New_Mexico.parquet,41214.0,8667.0,7172.0,939.0,6118.0,4922.0,2388.0,5182.0,6722.0,1709.0,7722.0,1039.0,15089.0,4191.0
32,all_New_York.parquet,419092.0,73228.0,38873.0,3443.0,50674.0,28848.0,11900.0,44110.0,52748.0,13980.0,80392.0,5919.0,80551.0,13848.0
33,all_North_Carolina.parquet,250092.0,55308.0,44016.0,6040.0,33435.0,30938.0,10641.0,32329.0,40822.0,9977.0,34280.0,9741.0,62275.0,19777.0
34,all_North_Dakota.parquet,10150.0,3419.0,2846.0,93.0,1734.0,1517.0,398.0,1978.0,1925.0,401.0,2638.0,36.0,3641.0,430.0
35,all_Ohio.parquet,258179.0,61359.0,35017.0,3912.0,43967.0,34967.0,16233.0,39005.0,35889.0,14834.0,63916.0,3619.0,52018.0,16463.0
36,all_Oklahoma.parquet,89205.0,16170.0,19934.0,2781.0,13792.0,17787.0,5806.0,11553.0,11617.0,4363.0,19759.0,2635.0,17642.0,7112.0
37,all_Oregon.parquet,102473.0,20166.0,13273.0,1992.0,15864.0,8311.0,5360.0,14843.0,13437.0,4188.0,31366.0,2139.0,21072.0,5467.0
38,all_Pennsylvania.parquet,239131.0,70597.0,35382.0,3793.0,37815.0,34358.0,10374.0,38564.0,40413.0,6844.0,45696.0,3899.0,53299.0,11419.0
39,all_Rhode_Island.parquet,26752.0,3345.0,2442.0,187.0,2855.0,1496.0,505.0,2204.0,2649.0,493.0,3338.0,68.0,7329.0,389.0
40,all_South_Carolina.parquet,136653.0,22725.0,23679.0,1885.0,15377.0,18709.0,5723.0,14497.0,15600.0,6177.0,12476.0,3979.0,28652.0,9275.0
41,all_South_Dakota.parquet,12130.0,3500.0,3090.0,80.0,1988.0,2610.0,557.0,1559.0,1373.0,174.0,3789.0,54.0,4901.0,656.0
42,all_Tennessee.parquet,161585.0,28586.0,37198.0,2542.0,21178.0,26067.0,7734.0,18342.0,22605.0,8963.0,20086.0,4673.0,39471.0,10693.0
43,all_Texas.parquet,290711.0,59999.0,47612.0,14377.0,55270.0,35039.0,18903.0,46398.0,55617.0,17216.0,36048.0,14286.0,69069.0,43930.0
44,all_Utah.parquet,104381.0,20617.0,10021.0,4619.0,10851.0,7008.0,15128.0,11598.0,10001.0,2903.0,26009.0,3963.0,19492.0,11103.0
45,all_Vermont.parquet,8333.0,2898.0,2390.0,72.0,1007.0,1303.0,89.0,943.0,812.0,110.0,1839.0,27.0,1589.0,262.0
46,all_Virginia.parquet,204775.0,44317.0,30377.0,3165.0,23575.0,24579.0,7890.0,24337.0,25592.0,11117.0,27945.0,3582.0,41978.0,11334.0
47,all_Washington.parquet,167580.0,31998.0,24992.0,4022.0,25153.0,11317.0,9266.0,25546.0,24863.0,6816.0,52742.0,2323.0,27725.0,12303.0
48,all_West_Virginia.parquet,30164.0,6507.0,7374.0,12.0,2656.0,7224.0,848.0,2458.0,2509.0,698.0,5498.0,327.0,5418.0,445.0
49,all_Wisconsin.parquet,124818.0,29737.0,25122.0,1605.0,19830.0,15742.0,6088.0,18679.0,15968.0,4898.0,37698.0,754.0,21743.0,6101.0
50,all_Wyoming.parquet,9439.0,2006.0,1873.0,65.0,1092.0,769.0,543.0,863.0,1036.0,300.0,2451.0,204.0,1838.0,331.0